server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mine-types: text/html, text/xml, txt/plain, text/css, text/javascript, application/javascript, application/json
    mine-response-size: 1024

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:123}
    url: jdbc:postgresql://${DB_HOSTNAME}/rinha
    username: ${DB_USERNAME:admin}
  jpa:
    open-in-view: false
    properties:
      hibernate:
      #        show_sql: true
      #        use_sql_comments: true
      #format_sql: true
  hikari:
    maximum-pool-size: 5
    auto-commit: false
